<a href="https://colab.research.google.com/github/Mujthaba-GM/Student-new1234/blob/main/Day2_Arrays-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
#Single Diamensional arrays using numpy
# functions size, dtype, reshape, sort, mean, max, min, argmin, agrmax, unique, copy
import numpy as np
# Create a single-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])  # Array 1 initialization
arr2=np.array([10,20,30,40,50])
print("Array 1:", arr1)  # Displaying Array 1
print("Array 1 slicing ",arr1[1:3])
print("Add of two arrays",arr1+arr2)
print("Sub of two arrays",arr1-arr2)
print("Data type of arr1",arr1.dtype)
print("Size of arr2",arr1.size)
print("Reshape of array 1",arr1.reshape(5,1))
arr3=np.array([20,10,2,3,4,15,1])
arr3.sort()
print("sort of array 3 elements",arr3)
print("Mean of array 3 is ",arr3.mean())
print("Max of array 1",arr1.max())
print("max of array 3 is ",arr3.max())
print("Min of array 3 is",arr3.min())
index=np.argmax(arr3)
print("Argmax of array3 is",index)
index1=np.argmin(arr3)
print("Argmin of array 3 is ",index1)
print("Unique in array1 is ",np.unique(arr1))
arr4=arr3.copy()
print("Creating separating copy of array 3",arr4)
print("Product of array1", np.prod(arr1))
print("Product of array2",np.prod(arr2))
print("prod of two arrays arr1 and arr2",np.prod(arr1)*np.prod(arr2))
print("Sum of arra1",np.sum(arr1))
print("Horizontal Stack:\n", np.hstack((arr1, arr2)))
print("Vertical Stack:\n", np.vstack((arr1, arr2)))





Array 1: [1 2 3 4 5]
Array 1 slicing  [2 3]
Add of two arrays [11 22 33 44 55]
Sub of two arrays [ -9 -18 -27 -36 -45]
Data type of arr1 int64
Size of arr2 5
Reshape of array 1 [[1]
 [2]
 [3]
 [4]
 [5]]
sort of array 3 elements [ 1  2  3  4 10 15 20]
Mean of array 3 is  7.857142857142857
Max of array 1 5
max of array 3 is  20
Min of array 3 is 1
Argmax of array3 is 6
Argmin of array 3 is  0
Unique in array1 is  [1 2 3 4 5]
Creating separating copy of array 3 [ 1  2  3  4 10 15 20]
Product of array1 120
Product of array2 12000000
prod of two arrays arr1 and arr2 1440000000
Sum of arra1 15
Horizontal Stack:
 [ 1  2  3  4  5 10 20 30 40 50]
Vertical Stack:
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [38]:
# Two-Dimensional arrays using NumPy
# Functions: size, dtype, reshape, sort, mean, max, min, argmin, argmax, unique, copy

import numpy as np

# Create two-dimensional arrays (2 rows × 5 columns)
arr1 = np.array([[1, 2, 3, 4, 5]])
arr2 = np.array([[10, 20, 30, 40, 50]])

print("Array 1:\n", arr1)  # Displaying Array 1
print("Array 1 slicing:\n", arr1[:, 1:3])  # Slice columns 1 to 2 from row 0

# Array addition and subtraction (element-wise)
print("Add of two arrays:\n", arr1 + arr2)
print("Sub of two arrays:\n", arr1 - arr2)

# Data type and size
print("Data type of arr1:", arr1.dtype)
print("Size of arr1:", arr1.size)

# Reshape example (reshaping arr1 into 5 rows and 1 column)
print("Reshape of array 1 to 5x1:\n", arr1.reshape(5, 1))

# Another array for sort and statistics
arr3 = np.array([[20, 10, 2, 3, 4, 15, 1]])
arr3.sort()
print("Sorted array 3 elements:\n", arr3)

# Statistics
print("Mean of array 3:", arr3.mean())
print("Max of array 1:", arr1.max())
print("Max of array 3:", arr3.max())
print("Min of array 3:", arr3.min())

# Index of max and min values
print("Argmax of array 3:", np.argmax(arr3))
print("Argmin of array 3:", np.argmin(arr3))

# Unique values
print("Unique elements in array 1:", np.unique(arr1))

# Copy of array
arr4 = arr3.copy()
print("Creating separate copy of array 3:\n", arr4)

# Product and sum
print("Product of array 1:", np.prod(arr1))
print("Product of array 2:", np.prod(arr2))
print("Product of both arrays (arr1 * arr2):", np.prod(arr1) * np.prod(arr2))
print("Sum of array 1:", np.sum(arr1))

# Stacking arrays
print("Horizontal Stack:\n", np.hstack((arr1, arr2)))
print("Vertical Stack:\n", np.vstack((arr1, arr2)))


Array 1:
 [[1 2 3 4 5]]
Array 1 slicing:
 [[2 3]]
Add of two arrays:
 [[11 22 33 44 55]]
Sub of two arrays:
 [[ -9 -18 -27 -36 -45]]
Data type of arr1: int64
Size of arr1: 5
Reshape of array 1 to 5x1:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Sorted array 3 elements:
 [[ 1  2  3  4 10 15 20]]
Mean of array 3: 7.857142857142857
Max of array 1: 5
Max of array 3: 20
Min of array 3: 1
Argmax of array 3: 6
Argmin of array 3: 0
Unique elements in array 1: [1 2 3 4 5]
Creating separate copy of array 3:
 [[ 1  2  3  4 10 15 20]]
Product of array 1: 120
Product of array 2: 12000000
Product of both arrays (arr1 * arr2): 1440000000
Sum of array 1: 15
Horizontal Stack:
 [[ 1  2  3  4  5 10 20 30 40 50]]
Vertical Stack:
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [39]:
# Pandas and its operations
import pandas as pd

# Create data using dictionary
data = {
    'name': ['Tom', 'Jerry', 'Anna'],
    'age': [20, 21, 19],
    'marks': [85, 90, 88]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print the whole DataFrame
print("Student Data:\n", df)

# Print first row
print("\nFirst row:\n", df.head(1))

# Print only names
print("\nNames:\n", df['name'])

# Add 5 bonus marks to each student
df['total'] = df['marks'] + 5
print("\nAfter adding bonus marks:\n", df)

# Sort by marks
df_sorted = df.sort_values(by='marks')
print("\nSorted by marks:\n", df_sorted)

# Average marks
print("\nAverage marks:", df['marks'].mean())


Student Data:
     name  age  marks
0    Tom   20     85
1  Jerry   21     90
2   Anna   19     88

First row:
   name  age  marks
0  Tom   20     85

Names:
 0      Tom
1    Jerry
2     Anna
Name: name, dtype: object

After adding bonus marks:
     name  age  marks  total
0    Tom   20     85     90
1  Jerry   21     90     95
2   Anna   19     88     93

Sorted by marks:
     name  age  marks  total
0    Tom   20     85     90
2   Anna   19     88     93
1  Jerry   21     90     95

Average marks: 87.66666666666667


In [1]:
import pandas as pd
import os

# 1. Create and write to a text file
text_path = r"D:\abcd.txt"
with open(text_path, "w") as f:
    f.write("I love India")

# 2. Create DataFrame
data = {
    'slno': [1, 2, 3],
    'name': ['Tom', 'Jerry', 'Anna'],
    'marks': [85, 90, 88]
}
df = pd.DataFrame(data)

# 3. Save DataFrame to CSV
csv_path = r"D:\datanew.csv"
df.to_csv(csv_path, index=False)

# 4. Show outputs in console
print("✅ Text file content:")
with open(text_path, "r") as f:
    print(f.read())

print("\n✅ DataFrame:")
print(df)

print(f"\n✅ CSV file 'datanew.csv' saved successfully at: {csv_path}")

✅ Text file content:
I love India

✅ DataFrame:
   slno   name  marks
0     1    Tom     85
1     2  Jerry     90
2     3   Anna     88

✅ CSV file 'datanew.csv' saved successfully at: D:\datanew.csv


Content of abcd.txt:
I love India

Content of data.txt:
I love India
